### ISSUE TITLE
[Bug] UI :: Player score sometimes erratic @ 20180813

### ISSUE THREAD

**Issue by nathaniel-gray** [TeamVelocity/teamvelocity.github.io#11]
- When: Single player game, round 2
- What: Player score become erratic - hard to diagnose (working on specifics)
-- Bankrupt with $3000 didn't bankrupt player
-- Valid completion of 60% of round 2 board did not
-- Double score not double value of next wheel spin 
--> it is believed that double score would:
---> double current question score
---> continue with active player answering the selected category
---> not switch active player

Suspect: End of round two (in single player game) shows 4 active players
![image](https://user-images.githubusercontent.com/40145468/44067460-9c6a531a-9f43-11e8-82ed-bdf7b65622ba.png)

**Comment by nathaniel-gray** [comment]
@bmweiner Double Score might have conflicting definitions:
- Based on current game play, the double score appears to double the player's active score
- I thought (perhaps wrongly) that it was supposed to double the active question's worth

As current, the person that lands on it, in a late game scenario, has a really large chance of winning assuming no bankrupt situation occurs.

Working out the logic seems fine - if we let the current game play roll, we should update the messaging upon landing on it, to show something like, "You've landed on Double Score! Your player score just doubled!"

**Comment by bmweiner** [comment]
> One “Double your Score” sector. When this sector comes up, the player’s score is doubled (even if it is negative).

Basically this should double the players current round score, even if negative, so it could result in a really good outcome or bad :-) I wasn't able to replicate this bug. I've been pushing a lot of updates, I suppose it's possible that the cache somehow made the source files out of sync, but that would be weird.

**Comment by bmweiner** [comment]
Let's keep this open and revisit during tomorrow's meeting to see if it happens again.

**Comment by bmweiner** [comment]
I think i figured out the issue here, the reset action was not removing players from the game API, so it would add new players every time the user reset and clicked let's play. This should be fixed now.
