### ISSUE TITLE
[Bug] Game - Reset fails to reinitialize game board to editable

### ISSUE THREAD

**Issue by nathaniel-gray** [TeamVelocity/teamvelocity.github.io#13]
[Bug] Game - Reset fails to reinitialize game board to editable
- When: 1-3 players, game play initiated at least once
- What:
-- Game state resets to the "let's play" - game running state
-- Game board becomes uneditable once game play has begun at least once

**Comment by bmweiner** [comment]
This should be fixed now, it was linked to the timer.stop() error which stopped the code block from reaching the lines to show/hide the display elements.
