### ISSUE TITLE
End of Round Experience (not finished)::Board Depleted

### ISSUE THREAD

**Issue by bmweiner** [TeamVelocity/teamvelocity.github.io#5]
- What: 
-- multiple users experience green "active" player borders
-- No transition occurs to move from board 0 to board 1; e.g. game stuck
- When: End of round via board category clues depleted

**Comment by bmweiner** [comment]
I added support to change rounds.

**Comment by bmweiner** [comment]
@nathaniel-gray please confirm and i will close this issue

**Comment by nathaniel-gray** [comment]
@bmweiner Confirmed @ 20180812 :: 2346 that round transitions to round 2.

However, # of spins, and # clues available in round does not reset during the round change. E.g. 3rd spin in second round results in -3 spins left, counting down toward -<number>.

Up to you if you want to spawn a new bug about this, or keep this open.

Notes: I don't think we formally defined what should happen across rounds with the player's current bundle of free tokens. As you've currently implemented, the score and tokens move between rounds.

**Comment by nathaniel-gray** [comment]
![image](https://user-images.githubusercontent.com/40145468/44012065-8a033e1c-9e8a-11e8-83cb-872c38999bfc.png)

**Comment by bmweiner** [comment]
This is definitely a bug. I will fix it today

**Comment by bmweiner** [comment]
Hi @nathaniel-gray this issue should be fixed now.

Regarding the tracking of points and tokens. The tokens carry between both rounds. The score logic tracks scores by round (e.g. bankrupt only affects the current round). The score displayed under the player is their current total between both rounds.
