### ISSUE TITLE
[Bug] Free Turn changes active player

### ISSUE THREAD

**Issue by nathaniel-gray** [TeamVelocity/teamvelocity.github.io#6]
[Bug] Free turn @ 20180812
- When: Active player spin lands on Free turn
- What: Current player advanced to next player
- Expected: Active player assigned free turn should maintain control of Wheel for next spin.

**Comment by bmweiner** [comment]
> One “free turn” sector. When this sector comes up, the player gets a token for a free turn later in the game. The token could be used if the player loses his turn by spinning a “lose turn” or answering a question incorrectly in a future turn. If this happens, the player could redeem the token and would get to spin the wheel again. The number of tokens is unlimited.

I believe the expected behavior should be landing on free-turn should end the users turn. The user can use that token on a subsequent turn where they spin lose turn or have an invalid answer.

Does this sound ok?

**Comment by bmweiner** [comment]
@nathaniel-gray agreed via Slack. Closing this one.
