### ISSUE TITLE
score when time is up

### ISSUE THREAD

**Issue by monaram** [TeamVelocity/teamvelocity.github.io#8]
When time is up, it ask the player to verify the answer and when the answer is verified as correct, it adds value to the player’s score even though the player ran out of time. It shouldn’t add or subtract any points from the player and the player should lose the turn.

**Comment by bmweiner** [comment]
>There should be a time limit on answering a question. If the time expires, no points are subtracted from the player’s score, but he loses his turn. If he has a token, he can redeem it for another spin.

Good catch! I will fix this.

**Comment by bmweiner** [comment]
Fixed this, also added a grey color on the board square to indicate the question was neither correct (green) or incorrect (red)
