### ISSUE TITLE
[bug] UI Timer Class @ 20180813

### ISSUE THREAD

**Issue by nathaniel-gray** [TeamVelocity/teamvelocity.github.io#9]
[bug] UI Timer Class @ 20180813
- What: stop property on timer in UI.js throws type error. timer not a valid reference at the stopTimer function facet.
- Message: Uncaught TypeError: Cannot read property 'stop' of undefined
- Where: ui.js :: 855
stopTimer: function(){
        wheel.timer.stop();
    },

**Comment by bmweiner** [comment]
Do you know at what point in the gameplay this occurred? can you snap a screenshot? thx!

**Comment by bmweiner** [comment]
Was this by chance happening if you clicked -> Let's Play then -> reset immediately. If so, that should be fixed now.

**Comment by nathaniel-gray** [comment]
@bmweiner Concur - the reset error related to this identified error is gone as of 20180815. The reset issues 17 and 18 appear to have arisen during recent reset-related churn though. Marking this defect closed.
